---

- name: Install marathon
  apt: name=marathon
  notify:
      - Restart marathon
  tags:
      - mesos
      - marathon

- name: Start marathon
  service:
      name: marathon
      state: started
  tags:
      - mesos
      - marathon
